daily_task:
  class: "DailyStatsJob"
  every: "1.day"
  at: "7:00"

weekly_task:
  class: "WeeklyStatsJob"
  every: "1.week"
  at: "Tue 9:00"

yearly_task:
  class: "YearlyStatsJob"
  every: "1.year"
  at: "Sat 1:00"
